### ISSUE TITLE
Hexadecimal being displayed in .svg file instead of UTF-8 (dbdia 0.3)

### ISSUE THREAD

**Issue by w3slley** [edrdo/dbdia#3]
When saving the database schema/ER model into a .svg file, this is what I get:
![image](https://user-images.githubusercontent.com/24323626/91882087-669dbc00-ec7a-11ea-842b-c4db941394a9.png)
It looks like instead of displaying the UTF-8 characters, dbdia is displaying the hexadecimal representation of them. I don't know whether this is an error with my setup or with the tool itself though. I tried saving with other formats (png and jpg) and they are working fine. Have you encounter something like this before?

Thanks in advance.

**Comment by edrdo** [comment]
Can you please provide the input file so that I can try to reproduce the issue ?  

The problem may be due to character encoding settings when opening the input file. dbdia does not set the character encoding to use (it inherits the default in use by the JVM) and I think antlr does not also. I'll have to investigate this and if it is doable to accept a parameter for the file encoding (I think so).

Meanwhile, as a temporary workaround, it may be that setting the `-Dfile.encoding=UTF-8 ` on VM startup solves the problem, e.g. you may patch the `dbdia` script as follows:

`
java -Dfile.encoding=UTF-8 -cp $(dirname $0)/dbdia-0.3.jar dbdia.Main $* 
`

**Comment by edrdo** [comment]
Thanks.  Sorry, I forgot to ask for the output SVG file also, you can add it as an attachment in this thread). The changes I mentioned are to the `dbdia` script file found in the bin directory of the dbdia release, assuming you're using Linux or MacOS. If using Windows, edit `dbdia.bat` instead in .  Just add `-Dfile.encoding=UTF-8` without changing other arguments.  I did some commits to force UTF-8 encoding for both the input and the files fed to dot (dot in turn  uses UTF-8 default) but I'll have to test them still.

**Comment by w3slley** [comment]
[Here](https://github.com/edrdo/dbdia/files/5169950/files.zip) is the file with the .er input file and the .svg image returned as output. I made the changes to the `bin/dbdia` script (I use linux) however the result was still the same as before.

**Comment by edrdo** [comment]
The problem is really only due to the program you are using to visualize the SVG file. Opening the SVG file using Firefox or Chrome works fine. The following is shown: 

<img width="713" alt="sc" src="https://user-images.githubusercontent.com/1699245/92179769-4a964800-ee3d-11ea-81b7-46899e7efe6a.png">

If you open the SVG file using a text editor you'll see that it is encoded in the UTF-8. 
At the beginning you will see: 

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
 "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- Generated by graphviz version 2.43.0 (0)
 -->
...

```

**Comment by w3slley** [comment]
You are right. I'm sorry about that. Thank you for answering!
